# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build & Publish NuGet packages

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Release mode"
        required: true
        type: choice
        default: dry-run
        options:
          - dry-run
          - release

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job
    runs-on: windows-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v6

    - name: Extract version from Versions.props
      id: version
      run: |
        [xml]$xml = Get-Content Versions.props
        $version = $xml.Project.PropertyGroup.Sqlite3MCVersion
        echo "VERSION=$version" >> $env:GITHUB_ENV
        echo "version=$version" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - name: Download release archive
      shell: bash
      run: |
        VERSION=${{ steps.version.outputs.version }}
        TAG=v$VERSION
        ARCHIVE=release-$TAG.tar.gz
        curl -L \
          -o $ARCHIVE \
          https://github.com/utelle/SQLite3MultipleCiphers-cb/releases/download/$TAG/$ARCHIVE

    - name: Verify archive exists
      shell: bash
      run: |
        VERSION=${{ steps.version.outputs.version }}
        TAG=v$VERSION
        ARCHIVE=release-$TAG.tar.gz
        if [ ! -f "$ARCHIVE" ]; then
          echo "Archive not found!"
          exit 1
        fi

    - name: Extract binaries
      shell: bash
      run: |
        VERSION=${{ steps.version.outputs.version }}
        TAG=v$VERSION
        ARCHIVE=release-$TAG.tar.gz
        mkdir -p cb/bld/bin
        tar -xzf release-$TAG.tar.gz -C cb/bld/bin

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x

    - name: Setup .NET for Android and iOS
      run: dotnet workload install android ios

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Show list of NuGet packages
      run: Get-ChildItem -Recurse "artifacts\package\release"

    # -------------------------------------------------
    # MODE INFO
    # -------------------------------------------------
    - name: Release mode info
      run: |
        VERSION=${{ steps.version.outputs.version }}
        TAG=v$VERSION
        ARCHIVE=release-$TAG.tar.gz
        echo "=============================="
        echo "MODE: $MODE"
        echo "VERSION: $VERSION
        echo "ARCHIVE: $ARCHIVE"
        echo "=============================="

        case "$MODE" in
          dry-run)
            echo "🧪 DRY RUN MODE (build tested, no release)"
            ;;
          release)
            echo "🚀 REAL RELEASE MODE (will publish)"
            ;;
        esac

    # Get a short-lived NuGet API key
    - name: NuGet login (OIDC → temp API key)
      if: ${{ inputs.mode == 'release' }}
      uses: NuGet/login@v1
      id: login
      with:
        user: ${{ secrets.NUGET_USER }}
    
    # Push the packages
    - name: Push NuGet packages
      if: ${{ inputs.mode == 'release' }}
      shell: pwsh
      run: |
        $packages = Get-ChildItem -Path "artifacts/package/release" -Filter "*.nupkg"
        foreach ($pkg in $packages) {
            Write-Host "Pushing $($pkg.FullName)"
            dotnet nuget push $pkg.FullName --api-key $env:NUGET_API_KEY --source https://api.nuget.org/v3/index.json
        }
      env:
        NUGET_API_KEY: ${{ steps.login.outputs.NUGET_API_KEY }}
